diag_log "--------------------------------------------------------------------";
diag_log "-------------------Starting RoamingDM Server------------------------";
diag_log "----------------------------Version 1.1-----------------------------";
diag_log "-----------------------Written By Genetic---------------------------";
diag_log "--------------------------------------------------------------------";
diag_log "----------------------Disabling Player Fatigue----------------------";
diag_log "----------------------Player Fatigue Disabled-----------------------";
diag_log "----------------------------Setup Key Bindings----------------------";
systemChat format ["Welcome %1 To The DEATHMATCH", profileName];
setViewDistance 3000;
